
ALTER TABLE OUTLET
  ADD CONSTRAINT Outlet_Manager_FK FOREIGN KEY (ManagerNo) REFERENCES EMPLOYEE (EmpNo);

ALTER TABLE VEHICLE
  ADD CONSTRAINT Vehicle_Outlet_FK FOREIGN KEY (OutNo) REFERENCES OUTLET (OutNo);

ALTER TABLE EMPLOYEE
  ADD CONSTRAINT Employee_Outlet_FK FOREIGN KEY (OutNo) REFERENCES OUTLET (OutNo);
ALTER TABLE EMPLOYEE
  ADD CONSTRAINT Supervisor_Employee_FK FOREIGN KEY (SupervisorNo) REFERENCES EMPLOYEE (EmpNo);

ALTER TABLE FAULTREPORT
  ADD CONSTRAINT Faultreport_Employee_FK FOREIGN KEY (EmpNo) REFERENCES EMPLOYEE (EmpNo);
ALTER TABLE FAULTREPORT
  ADD CONSTRAINT Faultreport_License_FK FOREIGN KEY (LicenseNo) REFERENCES VEHICLE (LicenseNo);
ALTER TABLE FAULTREPORT
  ADD CONSTRAINT Faultreport_Rental_FK FOREIGN KEY (RentalNo) REFERENCES RECHARGEMENT (RentalNo);

ALTER TABLE RECHARGEMENT
  ADD CONSTRAINT Rechargement_Client_FK FOREIGN KEY (ClientNo) REFERENCES CLIENT (ClientNo);
ALTER TABLE RECHARGEMENT
  ADD CONSTRAINT Rechargement_License_FK FOREIGN KEY (LicenseNo) REFERENCES VEHICLE (LicenseNo);

-- Add constraints complete.




